version: '2'

services:
  api-server:
    image: 'analytics-dev-test:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: analytics-server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/analytics
      - SPRING_DATASOURCE_USERNAME=analyticsrw
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5231:5432"
    container_name: db
    environment:
      - POSTGRES_USER=analyticsrw
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=analytics

#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=analytics
#      - APP_DB_USER=analyticsrw
#      - APP_DB_PASS=password123
#      - APP_DB_NAME=analytics

# remember to build new jar.
# docker build --tag analytics-dev-test:latest .